server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://username:passwd@IP/mongodb_chat?retryWrites=true&w=majority&appName=dev
#      host: localhost
#      port: 27017
#      username: admin
#      password: admin
#      database: mongodb_chat
#      authentication-database: admin

springdoc:
  swagger-ui:
    path: /swagger-ui
    filter: true
    operations-sorter: alpha
    tags-sorter: alpha
    groups-order: asc
    layout: BaseLayout
    display-request-duration: true
#  show-actuator: true

logging:
  level:
    com:
      vedha: DEBUG

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    env:
      show-values: always
    configprops:
      show-values: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true